# HTTP -> HTTPS
server {
    listen 80;
    server_name convert-api.mediameta.net;

    return 301 https://$host$request_uri;
}

# HTTPS
server {
    listen 443 ssl;
    server_name convert-api.mediameta.net;

    root /var/www/public;
    index index.php index.html;

    ssl_certificate /etc/letsencrypt/live/convert-api.mediameta.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/convert-api.mediameta.net/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}